### ISSUE TITLE
Tried running your evolutionary code and hit an error

### ISSUE THREAD

**Issue by ifed-ucsd** [VITA-Group/TEGNAS#4]
I cloned your repo and ran
`python evolution_launch.py --space darts --dataset cifar10 --gpu 0`

I got the following error:

/workspace/TEGNAS/lib/procedures/ntk.py:60: UserWarning: torch.symeig is deprecated in favor of torch.linalg.eigh and will be removed in a future PyTorch release.
The default behavior has changed from using the upper triangular portion of the matrix by default to using the lower triangular portion.
L, _ = torch.symeig(A, upper=upper)
should be replaced with
L = torch.linalg.eigvalsh(A, UPLO='U' if upper else 'L')
and
L, V = torch.symeig(A, eigenvectors=True)
should be replaced with
L, V = torch.linalg.eigh(A, UPLO='U' if upper else 'L') (Triggered internally at  /opt/conda/conda-bld/pytorch_1634272178570/work/aten/src/ATen/native/BatchLinearAlgebra.cpp:2499.)
  eigenvalues, _ = torch.symeig(ntk)  # ascending
Traceback (most recent call last):
  File "./R_EA.py", line 458, in <module>
    main(args, nas_bench)
  File "./R_EA.py", line 408, in main
    model.accuracy, _, _time_cost_training = proxy_inference(xargs, model.arch, nas_bench, logger, -1, dataname, te_reward_generator)
  File "./R_EA.py", line 224, in proxy_inference
    _ = te_reward_generator.step(genotype2mask_darts(arch))
  File "/workspace/TEGNAS/lib/procedures/te_reward_generator.py", line 244, in step
    results = self.get_ntk_region_mse(self._xargs, arch_parameters, self._loader, self._region_model)
  File "/workspace/TEGNAS/lib/procedures/te_reward_generator.py", line 192, in get_ntk_region_mse
    LRs = region_model.forward_batch_sample()
  File "/workspace/TEGNAS/lib/procedures/linear_region_counter.py", line 266, in forward_batch_sample
    return [LRCount.getLinearReginCount() for LRCount in self.LRCounts]
  File "/workspace/TEGNAS/lib/procedures/linear_region_counter.py", line 266, in <listcomp>
    return [LRCount.getLinearReginCount() for LRCount in self.LRCounts]
  File "/workspace/TEGNAS/lib/procedures/linear_region_counter.py", line 169, in getLinearReginCount
    self.calc_LR()
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/TEGNAS/lib/procedures/linear_region_counter.py", line 145, in calc_LR
    res += res.T
RuntimeError: unsupported operation: some elements of the input tensor and the written-to tensor refer to a single memory location. Please clone() the tensor before performing the operation.

**Comment by chenwydj** [comment]
Hi @ifed-ucsd,

Thanks for your interest in our work!

I never met this error before, and I am not sure if I can reproduce this error. Could you double-check your system versions? We used CUDA 11.0 and pytorch==1.9.0.
